sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t sftwri/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true sftwri/docker-react2 npm run test
